### ISSUE TITLE
Legality's Autofix date

### ISSUE THREAD

**Issue by ForcedToRock** [BernardoGiordano/PKSM-Tools#1]
It'd be even better if it makes the date the same as the one on the 3DS' clock. Currently it universally sets it to 1/1/2000.

**Comment by architdate** [comment]
The auto legality is done on the PC so there is no real way of determining your 3DS date. However this can be done with the PC datetime.

**Comment by ForcedToRock** [comment]
It still sets the Egg Received Date as 1/1/2000. Looking at the code, I changed this setting to the current date and it did so (9/4/2017). It does set the egg hatch date as the current one. Perhaps I should've been more specific to my request, as I meant more the egg received date. My apologies.

![egg](https://user-images.githubusercontent.com/10488946/30029911-27540a1a-9159-11e7-9408-268f35160b5a.png)
