### ISSUE TITLE
Darmanatan and Victini Codes not compiling

### ISSUE THREAD

**Issue by PKMWM1** [BernardoGiordano/PKSM-Tools#14]
I'm trying to compile the new scripts for Black & White that allow for resetting Darmantan and Victini encounters, but even though all the other codes compile just fine. These codes just won't appear in the bw folder. I just copied the updated scripts.bat file and yet, they still won't compile.

**Comment by trainboy2019** [comment]
What happens when you try to compile?

**Comment by BernardoGiordano** [comment]
@trainboy2019 you missed the `-i` in both, I didn't notice

**Comment by trainboy2019** [comment]
Ah, I set up a script to format it similar to the others since I have to run the scripts slightly differently, I guess I forgot to have it add the -i.
