### ISSUE TITLE
Scripts that are obviously hacking

### ISSUE THREAD

**Issue by SpiredMoth** [BernardoGiordano/PKSM-Tools#16]
A legality discussion earlier prompted me to consider that a few of our scripts have results that would show some kind of hacking was done on the file(s). I've made a list of the ones I know fall into this and included the reasons (some reasons may even be incomplete):

- [all versions] "Set Vivillon Fancy form" (event exclusive pattern)
- [all versions] "Set Vivillon Pokeball form" (event exclusive pattern)
- [SM] "Give all items 99x" (Dream Ball, Sport Ball, Safari Ball, Cherish Ball)
- [SM] "All Z-Crystals Owned" (? - are there unreleased event-exclusive ones?)
- [ORAS] "Give all items 99x" (Dream Ball, Park Ball, Sport Ball, Moon Ball, Friend Ball, Love Ball, Heavy Ball, Lure Ball, Level Ball, Fast Ball, Safari Ball, Cherish Ball, non-Normal Type Gems)
- [XY] "Give all items 99x" (Park Ball, Sport Ball, Moon Ball, Friend Ball, Love Ball, Heavy Ball, Lure Ball, Level Ball, Fast Ball, Safari Ball, Cherish Ball, non-Normal Type Gems)
- [HGSS] "Give all pokeballs 99x" (Cherish Ball, Sport Ball, Park Ball)
- [PT] "Give all pokeballs 99x" (Cherish Ball)
- [DP] "Give all pokeballs 99x" (Cherish Ball)

Should we remake the item ones with the illegal items removed?
In the future, should we not include these kinds of scripts in releases?
Should those of us making scripts actively avoid making these kinds of scripts?

**Comment by trainboy2019** [comment]
I don't think removing them is the best idea, but maybe put a disclaimer?

**Comment by SpiredMoth** [comment]
My concern is more about including pre-compiled versions in the release. There's likely a lot of users that would like to use some of these, but prefer to keep their game as legit looking as possible. These same users might not consider that these scripts (as they currently are) could ruin that.

I'm fine with leaving them in the bat as they are. If someone really wants it that bad, they're free to compile it themselves or have someone do it for them. Then it wouldn't be their fault alone if they get caught for hacking.

**Comment by Multimegamander** [comment]
ummmmm, (im not a noob in the scene) how do I use these? they are  .bin, shoudn´t the be .pksm?

**Comment by BernardoGiordano** [comment]
Someone should fill a readme with a little description and disclaimer for each script, to avoid confusion

**Comment by SpiredMoth** [comment]
@Multimegamander The `.bin` files in the repo are resources used in compiling the scripts into `.pksm`, some of which you can find in `PKSMScript.zip` in the releases.

@BernardoGiordano I can start adding descriptions to the readme. Any ideas/preferences on formatting?

**Comment by architdate** [comment]
A good one would be: @SpiredMoth 
**Bold Script Title** : Standard text description `Note: in single line code quotes`

**Comment by architdate** [comment]
Closing, basic documentation handled in #31
