### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by worner47** [BernardoGiordano/PKSM-Tools#17]
Where exactly do i put the script files to get it to work on my pksm? Thank you in advance and sorry for the trouble.

**Comment by trainboy2019** [comment]
3ds/PKSM/script/<game>/
<game> can be 
usum
sm
oras
xy
b2w2
bw
hgss
pt
dp

**Comment by worner47** [comment]
Okay do I put that in the root of my ds?

**Comment by worner47** [comment]
Okay do I put that in the root of my

**Comment by worner47** [comment]
SD card I mean my bad and thank you

**Comment by trainboy2019** [comment]
On the root of your sd card, there should be a 3ds folder. In that folder, there should be a PKSM folder. in that folder there should be a scripts folder. Put the script in the game it's meant to be used for

**Comment by SpiredMoth** [comment]
The scripts go in `sd://3ds/PKSM/scripts/<game>` where `<game>` is one of the abbreviations trainboy mentioned above

**Comment by trainboy2019** [comment]
Oh my god, my email is exploding, but yes

**Comment by worner47** [comment]
Thank you very much
