### ISSUE TITLE
Unable to build serveLegality

### ISSUE THREAD

**Issue by Leonbabylon** [BernardoGiordano/PKSM-Tools#2]
I'm very new to developing in .net so excuse any stupid mistakes.
First i cloned the directory as is and tried to "dotnet build". This gave me the error: 

"C:\Users\Leon\Desktop\PKSM-Tools-master\serveLegality\serveLegality\serveLegality.csproj(118,5): error : Questo progetto fa riferimento a uno o più pacchetti NuGet che non sono presenti in questo computer. Usare lo strumento di ripristino dei pacchetti NuGet per scaricarli. Per altre informazioni, vedere http://go.microsoft.com/fwlink/?LinkID=322105. Il file mancante è ..\packages\Fody.2.0.0\build\dotnet\Fody.targets."

After Google translating (rofl) i figure out that a package called Fody was missing. i installed fody and costura using  "nuget restore -PackagesDirectory = packages.config" which installed Fody and Costura.Fody. I then Moved these into the parent directory and into a new Packages folder as specified in your .csproj file

Now attempting to "dotnet build" results in a different crash:

"C:\Program Files\dotnet\sdk\2.0.3\Microsoft.Common.CurrentVersion.targets(2925,5): error MSB4216: Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x86".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "C:\Program Files\dotnet\sdk\2.0.3\MSBuild.exe" exists and can be run. [C:\Users\Leon\Desktop\PKSM-Tools-master\serveLegality\serveLegality\serveLegality.csproj]"

I added a new line to the .csproj
\<GenerateResourceMSBuildArchitecture>CurrentArchitecture\</GenerateResourceMSBuildArchitecture>

now running dotnet build results in:

C:\Users\Leon\Desktop\Hmm\PKSM-Tools-master\serveLegality\packages\Fody.2.0.0\build\dotnet\Fody.targets(53,5): error MSB4062: The "Fody.WeavingTask" task could not be loaded from the assembly C:\Users\Leon\Desktop\PKSM-Tools-master\serveLegality\packages\Fody.2.0.0\build\dotnet\..\..\\Fody.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\Leon\Desktop\Hmm\PKSM-Tools-master\serveLegality\serveLegality\serveLegality.csproj]

Which has completely stumped me, i stated all steps in my troubleshooting incase its a problem of my own creation, any help is much appreciated.

**Comment by BernardoGiordano** [comment]
Make sure to download the NuGet packet `Costura.Fody` from the NuGet packet manager in VS

**Comment by Leonbabylon** [comment]
I don't have VS and am attempting to compile through powershell. Nuget restore did claim to install Costura.Fody

**Comment by BernardoGiordano** [comment]
did you solve this?
