### ISSUE TITLE
Unable to init connect, wrong interface being used with serveLegality?

### ISSUE THREAD

**Issue by tonyrayo** [BernardoGiordano/PKSM-Tools#3]
Salve BG! 👋 I have multiple physical as well as virtual network interfaces installed on my PC and this seems to be causing an issue with serveLegality.  I can connect normally using other tools (such as servepkx), however whenever I run serveLegality, the default local IP is 192.168.19.1 (I only use 192.168.1.* and 192.168.2.* for my physical network connections).  When I ran ipconfig, I found that this address was assigned to VMWare Network Adaptor VMnet8.  Unfortunately, unlike real network connections, VMnet1 and VMnet8 do not show a "disconnected" status like my physical ports do.

Changing the ip address to the correct one (192.168.1.153 for local and 192.168.1.159 for 3DS) does not fix the situation, but I believe this is due to the wrong adaptor still being used.  I will try to look into this matter more (as well as possibly hacking in a drop-down network adaptor selector), but if I don't create an issue on Github, it will slip my mind (as it has three times already 👅).

Edit: The network adaptor problem is a known issue when using `Dns.GetHostEntry(Dns.GetHostName())` .  The easiest solution seemed to be to look for an active gateway.  I was able to get it to display/use the correct IP on launch but experienced some odd behavior when trying to use PKSM (changing EV of selected Pokémon?) so more work needs to be done (or bug ignored since it doesn't seem to be affecting many others).

**Comment by tonyrayo** [comment]
My C# "raffazzonare".  It's likely overkill but seems to work in all cases.  Requires `using System.Linq;` and `using System.Net.NetworkInformation;` to be declared.

```cs
        public static string GetLocalIPAddress()
        {
                foreach (NetworkInterface ni in NetworkInterface.GetAllNetworkInterfaces())
                {
                    var addr = ni.GetIPProperties().GatewayAddresses.FirstOrDefault();
                    if (addr != null && !addr.Address.ToString().Equals("0.0.0.0"))
                    {
                        if (ni.NetworkInterfaceType == NetworkInterfaceType.Wireless80211 || ni.NetworkInterfaceType == NetworkInterfaceType.Ethernet)
                        {
                            foreach (UnicastIPAddressInformation ip in ni.GetIPProperties().UnicastAddresses)
                            {
                                if (ip.Address.AddressFamily == AddressFamily.InterNetwork)
                                {
                                    return ip.Address.ToString();
                                }
                            }
                        }
                    }
                }
                throw new Exception("Local IP Address Not Found!");
        }```

**Comment by BernardoGiordano** [comment]
I'll check the change in a couple days, thanks for the suggestion!
