### ISSUE TITLE
How to run servelegality

### ISSUE THREAD

**Issue by nicknicola** [BernardoGiordano/PKSM-Tools#32]
Hi, sorry if I am a noob, but trying to look for the exe, i rode the readme and it said in the section "Usage" to "Launch `serveLegality.exe`" so there is a exe, but not inside the Pksm-Tools folder.
Soo, in the section "Building" says "The executable can be built with any compiler that supports C# 7."
First, what is a compiler, and second, what files do i have to compile? I am using Ubuntu now, it works in this system or i need to use Windows? 
Thanks in advance!

**Comment by BernardoGiordano** [comment]
You're supposed to download the latest release. https://github.com/BernardoGiordano/PKSM-Tools/releases

**Comment by BernardoGiordano** [comment]
and, serveLegality is meant to work on windows, not on linux. Maybe you're able to use wine for that

**Comment by piepie62** [comment]
Wine does work for it

**Comment by nicknicola** [comment]
Thanks for the answer but I wanted to know how to run serveLegality. For what i saw, that are only the scripts to install on the 3ds for various cheats, but no relation with the serveLegality. 
Thanks for the hard work, and forgive me for insisting

**Comment by SpiredMoth** [comment]
PKSM-Tools v1.1.1 only contained scripts (only portion that had any updates), but v1.1.0 had everything

As for running serveLegality, try reading its readme [here](https://github.com/BernardoGiordano/PKSM-Tools/tree/master/serveLegality)

**Comment by nicknicola** [comment]
Yeah, i rode them: It says to Launch serveLegality.exe, but there is no exe. In the readme doesnt say how to compile the exe, so there was my question.

**Comment by SpiredMoth** [comment]
A precompiled `serveLegality.exe` is in serveLegality.zip in the v1.1.0 release

**Comment by nicknicola** [comment]
Ok, thanks!
