### ISSUE TITLE
D/P Single Item Scripts Don't work

### ISSUE THREAD

**Issue by PKMWM1** [BernardoGiordano/PKSM-Tools#37]
Whenever I try to use one of the single item scripts for Diamond or Pearl, such as the x999 Heart Scales, the game crashes when I open my bag. The item scripts for other pockets, such as Poke balls, TMs, and Battle Items work fine, but for some reason, regular item scripts make the entire bag unusable. I'd imagine that the offset is simply wrong.

**Comment by SpiredMoth** [comment]
You were correct about the offset being wrong. I could have sworn I had tested the single item scripts when I made them, but I guess I had taken it for granted that the DP Item pouch offset was correct.

I have double-checked that the offsets for DP are correct, and tested the Item pouch ones just to be sure. Fixed versions of the scripts will be in the next PKSMScript release, whenever that is.
